apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tmeit-app/deployment.yaml
- tmeit-app/poddisruptionbudget.yaml
- postgres/kubegres.yaml
- postgres/poddisruptionbudget.yaml
- postgres/kubegres-conf.yaml
- redis/redis-failover.yaml
