env:
    global:
        - secure: "W+60WPp/apDERyy4SI2xFSctwNdTwAaLKD7rCB154UnFHvyC+aXfyp2Cl930cuUpMDMAQ6BEVlfetPfaVXQTiHVSqR1DQSQJRal+g+ihLlPMquWaVADpjcGLdsO9XpPATFuYlwax8A/y1Jcl0nfAHoWZQYpygSskEnwCF4lKTIwB+YQaC+G/ouE9wc5UAzITxrBr/c+ZxL/oGppV/qbLg5qPHZG+79RIBcFyA+drHf/uQe6quW5ClqJTZU9UyKdaSNReayFqVCqloZ6yVlj+Sc3dALmCXn2Snn4Scux5RADdpn166ehsRWajE2yI4yNGuvrcy4Ys+SpJwK2qTi74sl1RRZS93gwRwIKBqudenlEiO5ZCCQPYfQYjaDauTPAybyHZyTAMQc3HMZTKdfamso0QLhWc7ekohbKEBDlZ/aHYXkXrt+/rr/f35dIS4wZUz/ulAc+2A1lqV8LlL9yBM7MUJOkbOXHBHETANV+ncIg5BuVjL/sT+mBagx3Bz/KeGGlzyW4AUoecyDxk1XjgMJcBbikG/7187XJ/ZlLsNYYO9efu4HaAIiqXUxG89fHpCZIxuevIJXHECTwdoIM0+PbSu7Sj5AjThQTR/lKx8M8anNs46EGc24VRddJxKyGjLyuO7JNSGO0yCRS0UEV9IMiYgu/+jNwA7PsDc6D1jJU="

matrix:
    include:
    
    # Backend #
      - language: python
        python:
            - "3.6"
        before_install:
            - cd back
        install:
            - pip install -r requirements.txt  # Install deps
            - pip install -r requirements_test.txt  # Install testing deps
            - pip install .  # Install our backend package
        script: pytest --cov=tmeit_backend tests
        after_success:
            - coveralls
        deploy:
            - provider: script
            script: echo deployed master
            on:
                branch: master
            - provider: script
            script: echo deployed testing
            on:
                branch: auto-deploy
            # (build docker image)
            # (push image to registry)

    # Frontend #
#      - language: node_js
#        node_js:
#            - "node"  # Use latest Node.js stable release
            
