matrix:
    include:
    
    # Backend #
      - language: python
        python:
            - "3.6"
        before_install:
            - cd back
        install:
            - pip install -r requirements.txt  # Install deps
            - pip install .  # Install our internal backend package
        before_script:
            mv tests/testing.sqlite3 tmeit_backend/testing.sqlite3
        script: pytest --cov=tmeit_backend tests  # Specify test dir to save time
        after_success:
            - coveralls
        
    # Frontend #
#      - language: node_js
#        node_js:
#            - "node"  # Use latest Node.js stable release
            
