env:
    global:
# SSH
         - secure: "W+60WPp/apDERyy4SI2xFSctwNdTwAaLKD7rCB154UnFHvyC+aXfyp2Cl930cuUpMDMAQ6BEVlfetPfaVXQTiHVSqR1DQSQJRal+g+ihLlPMquWaVADpjcGLdsO9XpPATFuYlwax8A/y1Jcl0nfAHoWZQYpygSskEnwCF4lKTIwB+YQaC+G/ouE9wc5UAzITxrBr/c+ZxL/oGppV/qbLg5qPHZG+79RIBcFyA+drHf/uQe6quW5ClqJTZU9UyKdaSNReayFqVCqloZ6yVlj+Sc3dALmCXn2Snn4Scux5RADdpn166ehsRWajE2yI4yNGuvrcy4Ys+SpJwK2qTi74sl1RRZS93gwRwIKBqudenlEiO5ZCCQPYfQYjaDauTPAybyHZyTAMQc3HMZTKdfamso0QLhWc7ekohbKEBDlZ/aHYXkXrt+/rr/f35dIS4wZUz/ulAc+2A1lqV8LlL9yBM7MUJOkbOXHBHETANV+ncIg5BuVjL/sT+mBagx3Bz/KeGGlzyW4AUoecyDxk1XjgMJcBbikG/7187XJ/ZlLsNYYO9efu4HaAIiqXUxG89fHpCZIxuevIJXHECTwdoIM0+PbSu7Sj5AjThQTR/lKx8M8anNs46EGc24VRddJxKyGjLyuO7JNSGO0yCRS0UEV9IMiYgu/+jNwA7PsDc6D1jJU="
         - secure: "T/olmgp9wBSH634L8fMTWNgaaxnVONWxWDdKVvD+yRtye30c7XKtrPsoUUSIiCI40+571nBCxFTb7Y3BL3DeEjfXV1thim9IFmWM1jms1jR47+2QMHNEtJwss5uPptFAwtaP/kYhiy1HRrX2uiLfcCkvOJ7ouAFdXorWDUo3ztWYkBMwBHLL27w8kDg9Wlf7s7dntV+Ur6PVUSym9iYmKDYAlwH20KCS16aURMuwzFGl1HOD0W21zSVMHnPBjEh46duE3U5L9MlRsFcUliCFqwVWwA2fLEDavtorx1yMICYR2+/OhqL3IO1t4bh0MA9XXwJEpY+KfYsWPcUQpnGXM/qlTRJ226G1ll9oD23/C2wXIE4bdC6aAkvQsIN1p+e/EidICoU6eISYjHKkBVWXoN9gBVlIfJzKXMCbXiKh71uMfNf1VLIsrJXhf6/cUnjTs/VR4lxPidhs/X26EM3ej07dh3OkA/GD7o8ofxonv1E6Xa8r+cS1MrxiP/56xqcKTHzHB/envTMIwKN9UbkwQLvJVN+0t+uF7ZxxlxHOUuecZDf8Wrze2uqOoOaVr8BlblywFxyVQtw/abEMZtD7PtGl+tu+WgTZpHbEZYmFDEbgURGkNCqB8Fcaodv2LgtdUrCUuYU66XVvsfayl0CWSrOuM6YSSuQBV085sTrcG44="
# Docker Hub
         - secure: "iAvW8bYw+GRnryXdJRR5AG4u9CqIzl6dh8CyUCY52c2zjkdKyrFu6NeZY89Y+czCC0CtM387SDTQojbDqPyoMrfveJpiuHwai/7Z88uovibWsiltg1GFRs/ErT5K9wEh6psuIWiTkRQ9GyZRO0hcrrurYGsYfabRlLCtq8P9RNcVDAVVb4eN3JNTbwnHMCeSKTp3XlYNnd9q3/93blepmVaXfJBZrN9WYgnwmDTz++P6IVfqffYNc1BRbnwL8gUJFfwAWL6HlHQ2679sv7ARTOHBCnptT8nVzeRpgy/2BY7hMDZOtwixylGTbIZEl5IrrdBPc9+6vvElPpdaOENutmwgy9zAIDXhdRfwXfhRy/kYBAsHV7afBEopS6RbolqFmhVv7UcrTgd3qZouc5vNFOVlLRanRcl/ooj2TpE336J5tJuNHUO3/fXxug1gkjGJe/21pO+zFt4UcGrKuU9H25lrtq8gBkKVZXh2I7tR8Ybxx1fNipdK/mSMStAJ1Zh0x1gts2s7yY2irPYnVXvJG/ek7q1PDD6lKs/SjXGKHz4IXTrctJGfsGZpP+0HuqBUJIv9V1RhhHn8LTeBwhzllnGRviEPi+F+G74pWHFvEFpnquksl9Lxp+m4595IjsZlWguCWEq/Gf/zDgft+oQ6ZXqYiGeA2K9WEjkDizbjGKI="
         - secure: "ZZ/Osed53+lo/q0ZrIAcsK7mKvsKNRHPZ2XlQh8pLf36kVkfzmsjQtRm95pWLqHVJMgWxrY73JmTA+KuHsNSwjTiJJaLvzEe83r5FaENe0J1wUyrK6fs+5g2qQMIkmg/EExNqZMVuJkfzIlMjK0CUprT8NCKA3tQ5pe0U7fbK+U6y2rN1ZBWFA1n0g8q7glcubEgr5X95IUygC4d3PW3QUWkO8/QkRD3MNQDwx17zGHZ1zWMduexI8eKJfiwdLI5MsxuFaX5f2/67DQ/w2Uybxp//kNhpMBcb1yBMn3PXv6EY12llA9CRa3CjGAIel5qiHF0YEQalrrrufruIVcg5/7gziPhKBEyTEWDQdxN/I6wNIT7tw78o5uNWuXr6Lu54tcdwnwg2SH2c4jQo6QIZtYkU4Q4EwGeFScWgRYdUtYVwInIPxkzC+szuwwZaQhYAoav8tZ6LT/tzIR16AF+SWRRXZpYif9i2BKU98ey7ck0ymOpDNxjVMQr0v2hvYPKzmlFJImUwCy4fhcgRnzZZxoy7+AcxRF6KpPLazDsDl1Lf4T5fuZvhlKLPyzN0ZnU5Jy1KYjc6ZEhUk0Lgc92tvwSIwSM5eoOmNMv3/xDUfRWur8854aPfRPiUH/Z4fZ3bHdtt5DDmfkBgCRd8N6fRG5OBdqqueVJqvMUat8KxVI="

services:
    - docker

matrix:
    include:
    
    # Backend #
      - language: python
        python:
            - "3.6"
        before_install:
            - cd back
            - /bin/bash build/build-dev.sh
        install: docker build -f build/Dockerfile.travis-test -t tmeit_backend-travis-test .
        script: docker run tmeit_backend-travis-test poetry run pytest
        deploy:
        # Production deploy on releases
#          - provider: script
#            script: bash deploy.sh
#            on:
#                tags: true
        # Development deploy on master commits
          - provider: script
            script: bash deploy_dev.sh
            on:
                branch: master

    # Frontend #
      - language: node_js
        node_js:
            - "node"  # Use latest Node.js stable release
        before_install:
            - cd front
        # Eventually do Jest testing here
        deploy:
        # Production deploy on releases
#          - provider: script
#            script: bash deploy.sh
#            on:
#                tags: true
        # Development deploy on master commits
          - provider: script
            skip_cleanup: true
            script: bash deploy_dev.sh
            on:
                branch: master

