FROM docker.io/library/mariadb:10.9

ENV MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true

WORKDIR /code

RUN apt update && apt install -y python3 python3-pip

RUN pip install poetry~=1.2

COPY back/pyproject.toml back/poetry.lock /code/

RUN poetry config virtualenvs.in-project true \
  && poetry install --no-interaction --no-ansi --with migrate

COPY back/ /code/

COPY ["old_website_migration/TMEIT.se Database.sql", "/dbdump.sql"]

COPY old_website_migration/entrypoint.sh /code

ENTRYPOINT ./entrypoint.sh

