apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
- tmeit-app/regcred.yaml
- create-test-db/job.yaml
- create-test-db/networkpolicy.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tmeit-app
    patch: |-
        - op: add
          path: /spec/template/spec/imagePullSecrets
          value: [{ name: regcred }]
  - target:
      group: batch
      version: v1
      kind: Job
      name: create-test-db
    patch: |-
        - op: add
          path: /spec/template/spec/imagePullSecrets
          value: [{ name: regcred }]

secretGenerator:
- name: kubegres-passwords
  literals:
  - superUserPassword=rzQ4aWQGkvWk8QfQkFPTjmE5ErJrpf
  - replicationUserPassword=7t3zfOH9GaFBjl4RA6gXIBhkImbsgw
  - tmeitBackendUserPassword=HBXOHEc6TpkquVHKy2zmSeUIEaUFvW

generatorOptions:
  disableNameSuffixHash: true
