apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
- tmeit-app/regcred.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tmeit-app
    patch: |-
        - op: add
          path: /spec/template/spec/imagePullSecrets
          value: [{ name: regcred }]
