"""added reset password columns

Revision ID: 2178001890f7
Revises: 8b45108e5c9d
Create Date: 2023-07-29 17:25:42.694546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2178001890f7'
down_revision = '8b45108e5c9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
