"""Add Member model

Revision ID: 2a101006d648
Revises: 
Create Date: 2022-05-29 19:06:49.310578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a101006d648'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('short_uuid', sa.String(), sa.Computed("replace(replace(encode(decode(left(replace(CAST(uuid AS VARCHAR), '-', ''), 12), 'hex'), 'base64'), '+', '-'), '/', '_')", ), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_email', sa.String(), nullable=False),
    sa.Column('current_role', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('drivers_license', sa.Boolean(), nullable=True),
    sa.Column('stad', sa.Date(), nullable=True),
    sa.Column('fest', sa.Date(), nullable=True),
    sa.Column('liquor_permit', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_members_login_email'), 'members', ['login_email'], unique=True)
    op.create_index(op.f('ix_members_short_uuid'), 'members', ['short_uuid'], unique=True)
    op.create_index(op.f('ix_members_uuid'), 'members', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_uuid'), table_name='members')
    op.drop_index(op.f('ix_members_short_uuid'), table_name='members')
    op.drop_index(op.f('ix_members_login_email'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
