"""Add old_username field and relation

Revision ID: 2b1dce5e197f
Revises: bd3a7cf57de1
Create Date: 2022-10-31 01:18:25.183951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1dce5e197f'
down_revision = 'bd3a7cf57de1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_website_migration', sa.Column('old_username', sa.String(), nullable=False))
    op.add_column('member_website_migration', sa.Column('migrated', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_member_website_migration_old_username'), 'member_website_migration', ['old_username'], unique=True)
    op.add_column('members', sa.Column('old_username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'members', 'member_website_migration', ['old_username'], ['old_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'old_username')
    op.drop_index(op.f('ix_member_website_migration_old_username'), table_name='member_website_migration')
    op.drop_column('member_website_migration', 'migrated')
    op.drop_column('member_website_migration', 'old_username')
    # ### end Alembic commands ###
