"""fix added columns for reset password model

Revision ID: 5163e3c880bc
Revises: 2178001890f7
Create Date: 2023-07-29 17:29:45.500571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5163e3c880bc'
down_revision = '2178001890f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
