"""Make MWM email nullable

Revision ID: 610eda95e782
Revises: 2b1dce5e197f
Create Date: 2022-10-31 18:10:24.404619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610eda95e782'
down_revision = '2b1dce5e197f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_website_migration_login_email_key', 'member_website_migration', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('member_website_migration_login_email_key', 'member_website_migration', ['login_email'])
    # ### end Alembic commands ###
