"""fix add date and time columns to events

Revision ID: a7ed421f8063
Revises: 8a1190b1d69e
Create Date: 2023-07-27 01:49:26.796877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7ed421f8063'
down_revision = '8a1190b1d69e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date_start', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('event_time_start', sa.String(), nullable=False))
    op.add_column('events', sa.Column('event_date_end', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('event_time_end', sa.String(), nullable=True))
    op.drop_column('events', 'event_date')
    op.drop_column('events', 'event_endtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_endtime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('events', 'event_time_end')
    op.drop_column('events', 'event_date_end')
    op.drop_column('events', 'event_time_start')
    op.drop_column('events', 'event_date_start')
    # ### end Alembic commands ###
