"""modify events table

Revision ID: f1f829d8b88c
Revises: fb9f5b398c71
Create Date: 2023-07-26 20:18:43.135873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1f829d8b88c'
down_revision = 'fb9f5b398c71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_owner', sa.String(), nullable=False))
    op.add_column('events', sa.Column('event_endtime', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_events_short_uuid', table_name='events')
    op.drop_column('events', 'sign_up_end_time')
    op.drop_column('events', 'short_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('short_uuid', sa.VARCHAR(), sa.Computed('replace(replace(encode(decode("left"(replace(((uuid)::character varying)::text, \'-\'::text, \'\'::text), 12), \'hex\'::text), \'base64\'::text), \'+\'::text, \'-\'::text), \'/\'::text, \'_\'::text)', persisted=True), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('sign_up_end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index('ix_events_short_uuid', 'events', ['short_uuid'], unique=False)
    op.drop_column('events', 'event_endtime')
    op.drop_column('events', 'event_owner')
    # ### end Alembic commands ###
