"""Add sign_ups table

Revision ID: fa7abd4aa843
Revises: 2a101006d648
Create Date: 2022-08-27 20:19:53.087461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa7abd4aa843'
down_revision = '2a101006d648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_ups',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('login_email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_sign_ups_login_email'), 'sign_ups', ['login_email'], unique=True)
    op.create_index(op.f('ix_sign_ups_uuid'), 'sign_ups', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sign_ups_uuid'), table_name='sign_ups')
    op.drop_index(op.f('ix_sign_ups_login_email'), table_name='sign_ups')
    op.drop_table('sign_ups')
    # ### end Alembic commands ###
