"""add events table

Revision ID: fb9f5b398c71
Revises: 8b45108e5c9d
Create Date: 2023-07-16 22:58:11.766419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9f5b398c71'
down_revision = '8b45108e5c9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('short_uuid', sa.String(), sa.Computed("replace(replace(encode(decode(left(replace(CAST(uuid AS VARCHAR), '-', ''), 12), 'hex'), 'base64'), '+', '-'), '/', '_')", ), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_time', sa.Date(), nullable=False),
    sa.Column('sign_up_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_events_short_uuid'), 'events', ['short_uuid'], unique=True)
    op.create_index(op.f('ix_events_uuid'), 'events', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_uuid'), table_name='events')
    op.drop_index(op.f('ix_events_short_uuid'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
