apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: tmeit-db
spec:
   replicas: 3
   image: postgres:15
   database:
      size: 200Mi
   customConfig: kubegres-conf
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: kubegres-passwords
              key: superUserPassword
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: kubegres-passwords
              key: replicationUserPassword
      - name: POSTGRES_TMEIT_BACKEND_PASSWORD
        valueFrom:
           secretKeyRef:
              name: kubegres-passwords
              key: tmeitBackendUserPassword
   resources:
     limits:
       memory: "150Mi"
       cpu: "200m"
       ephemeral-storage: 1Gi
     requests:
       memory: "75Mi"
       cpu: "50m"
       ephemeral-storage: 100Mi
  # Note: DB backups are not done with kubegres' built in backup system,
  # and are instead done with custom cronjobs found in deploy/kubernetes/tmeit-se/postgres/
  # This is done so that we can backup to Backblaze B2 storage,
  # and also so that we can have custom backup retention patterns,
  # i.e. hourly backups kept for 2 weeks, daily backups kept for a year, etc.
