# Job that runs all migrations for the production cluster

apiVersion: batch/v1
kind: Job
metadata:
  name: run-migrations
  labels:
    job: tmeit-db
spec:
  template:
    metadata:
      labels:
        job: tmeit-db
    spec:
      containers:
      - name: script
        image: tmeit-run-migrations:0.4.0
        imagePullPolicy: Always
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kubegres-passwords
                key: tmeitBackendUserPassword
        resources:
          requests:
            cpu: "50m"
            memory: "20Mi"
            ephemeral-storage: 500Mi
          limits:
            cpu: "100m"
            memory: "100Mi"
            ephemeral-storage: 500Mi
          securityContext:
            readOnlyRootFilesystem: true
      securityContext:
        runAsUser: 20001
        runAsGroup: 20001
      restartPolicy: Never
  backoffLimit: 10
