apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jwt-secret
spec:
  encryptedData:
    jwtSecret: AgDHowokGwtui3hGu0BP87CEvml5ZPzhHYSk0lXSXAjrUTt9HB6YDNvS6JDYqqNKkekG3qsGXfjFn3ORnZunFw6JX1SUZtnDyWBER9ViecvKfjVjF+W96pxXe/NP/90ncXbkkc+ZbTlzbvaq1YJZpTheu5CTMJ0CUOu1V8ZzhlWVmF3ev+M5shW6CBPeM9c+pRXJav/REtXrUWIdCjaW78uPED+vhj7P9r8ixjPyi+36eMvG2CdmsywpC3su3aREvJxY0JvZ/KrBcpO6Ut8ESAWs6hskrg1rEBgSYpNDLFCkRKiwNio0brUbWq/BTHw/ryD0UEekDg+NY/zsvhKAE3kUnNInBw+GMiEGriHqd9OjT9Hn7Mlrzm9ap3Jz5fBEjCzEzsOSkTPFiYHeMyPHfJOHfv9uFQ5oixI7GQPdd4/cmcdcy85Itq4tBGRHZGZJIMvP0EEWWHB851AcRX4yBnbLMyDvh/9zhfksU6LWWktzoziTM8lByNbmga3m1X60aIkxa3nSXaYQZVFGsderxN9BwbSU6Y4G4aIWUCL7ckmfU6K1r++lUVLYZda7kBDu5rJl5FXbU+aItBCJCfNcwayKuMq2cGYPy25aiy5WCoCXWh62Zxx2VfpNbGMZQz/9AkvP85oSD/ls9gl6KCh8oJ53QDV7fwEwafehvY+z3elrKN+HJyrUK03011R/I+F6eo6pQMVt2IkirhvP08e5qncYNDHb1kk0utjzT7xADKyWgmgXU2J7p/XABEq92/Vrijo=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jwt-secret

