apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: "docker.io/mailhog/mailhog:latest"
          ports:
            - name: http
              containerPort: 8025
            - name: smtp
              containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  ports:
    - port: 1025
  selector:
    app: mailhog
