[tool.poetry]
name = "tmeit_backend"
version = "0.1.0"
description = "Python backend for the TMEIT website"
authors = ["TraditionsMEsterIT"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.78.0"
PyJWT = "^2.4.0"
SQLAlchemy = "^1.3.3"
uvicorn = {extras = ["standard"], version = "^0.17.6"}

[tool.poetry.dev-dependencies]
coverage = "^4.5.2"
pytest = "^4.2.0"
pytest-cov = "^2.6.1"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
