swedish_last_names = {"class": "dataset", "label": "Rangordning efter efternamn och år", "source": "SCB",
              "updated": "2022-05-28T13:54:00Z", "id": ["Efternamn", "Tid"], "size": [109, 1], "dimension": {
        "Efternamn": {"label": "efternamn", "category": {
            "index": {"Abrahamsson": 0, "Ahmed": 1, "Ali": 2, "Andersson": 3, "Andreasson": 4, "Arvidsson": 5,
                      "Axelsson": 6, "Bengtsson": 7, "Berg": 8, "Berggren": 9, "Berglund": 10, "Bergman": 11,
                      "Bergqvist": 12, "Bergström": 13, "Björk": 14, "Björklund": 15, "Blom": 16, "Blomqvist": 17,
                      "Börjesson": 18, "Claesson": 19, "Dahl": 20, "Dahlberg": 21, "Danielsson": 22, "Ek": 23,
                      "Eklund": 24, "Ekström": 25, "Eliasson": 26, "Engström": 27, "Eriksson": 28, "Falk": 29,
                      "Forsberg": 30, "Fransson": 31, "Fredriksson": 32, "Gunnarsson": 33, "Gustafsson": 34,
                      "Göransson": 35, "Hansen": 36, "Hansson": 37, "Hassan": 38, "Hedlund": 39, "Hellström": 40,
                      "Henriksson": 41, "Hermansson": 42, "Holm": 43, "Holmberg": 44, "Holmgren": 45, "Holmqvist": 46,
                      "Håkansson": 47, "Isaksson": 48, "Ivarsson": 49, "Jakobsson": 50, "Jansson": 51, "Johansson": 52,
                      "Jonasson": 53, "Jonsson": 54, "Josefsson": 55, "Jönsson": 56, "Karlsson": 57, "Larsson": 58,
                      "Lind": 59, "Lindberg": 60, "Lindgren": 61, "Lindholm": 62, "Lindqvist": 63, "Lindström": 64,
                      "Lund": 65, "Lundberg": 66, "Lundgren": 67, "Lundin": 68, "Lundqvist": 69, "Lundström": 70,
                      "Löfgren": 71, "Magnusson": 72, "Martinsson": 73, "Mattsson": 74, "Mohamed": 75, "Månsson": 76,
                      "Mårtensson": 77, "Nilsson": 78, "Norberg": 79, "Nordin": 80, "Nordström": 81, "Nyberg": 82,
                      "Nyström": 83, "Olofsson": 84, "Olsson": 85, "Persson": 86, "Pettersson": 87, "Pålsson": 88,
                      "Samuelsson": 89, "Sandberg": 90, "Sandström": 91, "Sjöberg": 92, "Sjögren": 93, "Ström": 94,
                      "Strömberg": 95, "Sundberg": 96, "Sundqvist": 97, "Sundström": 98, "Svensson": 99,
                      "Söderberg": 100, "Söderström": 101, "Wallin": 102, "Viklund": 103, "Wikström": 104, "Åberg": 105,
                      "Åkesson": 106, "Åström": 107, "Öberg": 108},
            "label": {"Abrahamsson": "Abrahamsson", "Ahmed": "Ahmed", "Ali": "Ali", "Andersson": "Andersson",
                      "Andreasson": "Andreasson", "Arvidsson": "Arvidsson", "Axelsson": "Axelsson",
                      "Bengtsson": "Bengtsson", "Berg": "Berg", "Berggren": "Berggren", "Berglund": "Berglund",
                      "Bergman": "Bergman", "Bergqvist": "Bergqvist", "Bergström": "Bergström", "Björk": "Björk",
                      "Björklund": "Björklund", "Blom": "Blom", "Blomqvist": "Blomqvist", "Börjesson": "Börjesson",
                      "Claesson": "Claesson", "Dahl": "Dahl", "Dahlberg": "Dahlberg", "Danielsson": "Danielsson",
                      "Ek": "Ek", "Eklund": "Eklund", "Ekström": "Ekström", "Eliasson": "Eliasson",
                      "Engström": "Engström", "Eriksson": "Eriksson", "Falk": "Falk", "Forsberg": "Forsberg",
                      "Fransson": "Fransson", "Fredriksson": "Fredriksson", "Gunnarsson": "Gunnarsson",
                      "Gustafsson": "Gustafsson", "Göransson": "Göransson", "Hansen": "Hansen", "Hansson": "Hansson",
                      "Hassan": "Hassan", "Hedlund": "Hedlund", "Hellström": "Hellström", "Henriksson": "Henriksson",
                      "Hermansson": "Hermansson", "Holm": "Holm", "Holmberg": "Holmberg", "Holmgren": "Holmgren",
                      "Holmqvist": "Holmqvist", "Håkansson": "Håkansson", "Isaksson": "Isaksson",
                      "Ivarsson": "Ivarsson", "Jakobsson": "Jakobsson", "Jansson": "Jansson", "Johansson": "Johansson",
                      "Jonasson": "Jonasson", "Jonsson": "Jonsson", "Josefsson": "Josefsson", "Jönsson": "Jönsson",
                      "Karlsson": "Karlsson", "Larsson": "Larsson", "Lind": "Lind", "Lindberg": "Lindberg",
                      "Lindgren": "Lindgren", "Lindholm": "Lindholm", "Lindqvist": "Lindqvist",
                      "Lindström": "Lindström", "Lund": "Lund", "Lundberg": "Lundberg", "Lundgren": "Lundgren",
                      "Lundin": "Lundin", "Lundqvist": "Lundqvist", "Lundström": "Lundström", "Löfgren": "Löfgren",
                      "Magnusson": "Magnusson", "Martinsson": "Martinsson", "Mattsson": "Mattsson",
                      "Mohamed": "Mohamed", "Månsson": "Månsson", "Mårtensson": "Mårtensson", "Nilsson": "Nilsson",
                      "Norberg": "Norberg", "Nordin": "Nordin", "Nordström": "Nordström", "Nyberg": "Nyberg",
                      "Nyström": "Nyström", "Olofsson": "Olofsson", "Olsson": "Olsson", "Persson": "Persson",
                      "Pettersson": "Pettersson", "Pålsson": "Pålsson", "Samuelsson": "Samuelsson",
                      "Sandberg": "Sandberg", "Sandström": "Sandström", "Sjöberg": "Sjöberg", "Sjögren": "Sjögren",
                      "Ström": "Ström", "Strömberg": "Strömberg", "Sundberg": "Sundberg", "Sundqvist": "Sundqvist",
                      "Sundström": "Sundström", "Svensson": "Svensson", "Söderberg": "Söderberg",
                      "Söderström": "Söderström", "Wallin": "Wallin", "Viklund": "Viklund", "Wikström": "Wikström",
                      "Åberg": "Åberg", "Åkesson": "Åkesson", "Åström": "Åström", "Öberg": "Öberg"}}},
        "Tid": {"label": "år", "category": {"index": {"2021": 0}, "label": {"2021": "2021"}}}},
              "value": [89, 61, 36, 1, 92, 57, 25, 15, 24, 71, 32, 47, 54, 26, 46, 69, 88, 62, None, 63, 97, 82, 43, 87,
                        42, 79, 70, 41, 5, 76, 37, 53, 33, 48, 10, None, 95, 14, 65, 84, 83, 35, 80, 50, 56, 81, 100,
                        45, 52, None, 18, 13, 2, None, 12, None, 16, 3, 6, 28, 17, 23, 98, 22, 20, 75, 27, 29, 44, 30,
                        67, 58, 19, 91, 31, 38, 94, 66, 4, 99, 74, 64, 60, 55, 21, 7, 8, 11, 72, 51, 34, 73, 39, 86, 77,
                        93, 85, None, None, 9, 59, None, 40, 68, 49, 78, 96, None, 90],
              "status": {"18": "..", "35": "..", "49": "..", "53": "..", "55": "..", "97": "..", "98": "..",
                         "101": "..", "107": ".."}, "role": {"time": ["Tid"]}, "version": "2.0",
              "extension": {"px": {"infofile": "BE0001", "tableid": "TAB616", "decimals": 0}}}
