- op: add
  path: /spec/template/spec/initContainers
  value:
    - name: wait-for-migrations
      image: ghcr.io/groundnuty/k8s-wait-for:v1.6
      args:
        - "job"
        - "run-migrations"
      resources:
        requests:
          cpu: "8m"
          memory: "25Mi"
          ephemeral-storage: 10Mi
        limits:
          cpu: "80m"
          memory: "50Mi"
          ephemeral-storage: 100Mi
