apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jwt-secret
spec:
  encryptedData:
    jwtSecret: AgAi6CQiidMArlA20s6MfbHirsQXWdf8yKHUKnoaOGgtGIyknRRZrOfYZrWik+tLNdP6Gb7zEwjJOjvKkrr4q9BaHwLLdlYHp0M8gz4bhGZK281U7pKgbkYgjtrq8YaUy17cLsR5HJLYh7J+mnbQgTL/ESqybhPNucHEWF2i0Dvj7p6kM4jPxDrtyrVrEOv/fxtVq2pcD/hoVeSAfYgHUGtIEXiJFUjjvFBbu6/soCZlaUMJwgNrPPl8HyaH9BGWtnRcb3N5MqMkyr/uXKDVhC6EN6BvP6V5F7WKFhv34AuNyvY9iJGIs4396ZIHBAweBTFAcrMZaTE4Ut+T3zzWkw8ankKDQ1/XqP4+mmzK1vm5eoGVAHUBhDhfjiddk+xm9Y9UDV6L4EMwD7L2Mv6tUCF11eUh69RB0BnWG2NLxhC/q1CCWWRJImQ8TiDHol6NJ6Xaew0PWwRO7Zy/teTAdfxM2jRhnXi8C6YFMhonX6jrpl9IDIaKBLB4MRvSo6CbOB0jBXuPXyjuWUBbPgLKgtLfvrAmLhGdGwC9CJqj4tUX18AL+OBx8pmj6JXLIbNZhGLRj/yU1Nra3BJHglvAZvMMLr5XJx1Tp+lLRECrxtiQYiNZxLmakhh6uZCZFUi/pB0xa4N1M+zk6QHZzPBzPSZkROeCCQNawEjXKOEJUHTWlervNF+m5tK/QODl9L63LtiufrzzoLBgOYmLCJUwP1BHSou6cKxh9s42aovUSdlc6oLD10F18VfbZtBF5lz5CI+j+g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jwt-secret

