apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jwt-secret
spec:
  encryptedData:
    jwtSecret: AgCaJAgE1SSpUl1H5tZsOn6P6As3jT+e3mZ3kdOgUwHD4NUfl2zSu6upoTp52mFbGCf+lynJLfSyEVuwsmDW+3PMPMgKoTL1gpOLbKhmStEGGEJoG9mMzA6DVfkiev8UVhOzHxJqzG8gSLeDuk5tWY/yRvuP1xPe4FQdtZX37mHXsSqkDuQo5VFIOewkEAV9SUwtL1GiFxy4fEmSHuFxsVE6eHM+v75S/rppZfSgMo3uV3V3xnuJY04hLp5vaa8abX96xpu6hZYGZ4tfWruxQiumG/vnBNbBG11/d+keyzoG2dVbNH3SY0Gr1GvnZokwLLD4qIZIC4uAYcB8g70z0VCTAclWv6zzXLEnxD9+KCA9oi99SjiRBcozbWeRe5ka45iRQcAwIzskBhdPypib+sJdwtC6qRbKE7hCXLouBdpdsUO92IfAOufSLgFd467TYE7rBJ1KtlJtsQf3lot+A8qNxl2B7x2H48YImf/766Ql3TfTLq90Bniy8AjEUcS5+jk/45QpSPqu5JMiUmjhc2ABVe9GrznacMkqduCe97uS5zKZXHb8KHxFVLzJcOSo+9IWPE4tp7O4Bk2AnCXMButmvKymrYdPqkHQj1yHLFJgeahWoKHH4Q7jYiDxpZ8foaBjHZGMikekJcrkEZWC51NS17jfC8m6NC/abpx+s56Ni96+DSbQZb9BBUPk/dhB+sWJcHGvslP4WwLcDKF6CoSBnQpylQWSFnyn37o5Sp3ndsBCyIxVJGj6bFCCdpat/O+DjA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jwt-secret

