apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jwt-secret
spec:
  encryptedData:
    jwtSecret: AgAg+xKLbHMjB4sX48xK2AFIe41uUzo5yzb7Qd7rDA285YbhAMxm5kQ9oGnoFNWpZPC1BVLitflR6bXFWzM4OAp1zhmFh5bJbD8euVMx26DVdPlsJbva8QX4YRaHffNSznmYzDhhMndrHl+Z+RJcbpffvpM3NATdm/l8ICx6rq4vIp/iFTunD1NbBGZ3KGxVmcqqFd5E7KPA7E5KDrsQ6wNobndCdzLDD4SmhH5iHlHIMByPMtKGPtCuEVGCgO9dg2YUO414rw4eW/N4B32Ma3VjMYyDO9TmaGjZ65zJrfu2TR+6Hs0haSdiiy3Rvv25phTcazvZDxFJJzaRx+1QOX45ALI8ssyq4ve7qzLMNWnBFLE9ZpeR9JkL+BSjCe7T5Ht+RzFpp+CO4Woy4AeE0UdSIEp+EBAPah9y74I3VVoIFTdU9J9JiyqM0FWXizoRWKWv0dHCSjcj39DS8YLMGog/jes5/nirFFi/H0osUMYI7O0Nybllg/TzQ2hZGc3AQM134BalaR6cWpR7kBNrpxeIp4in3dYcOqETJUhSj6Unuzmd2zxi3QsFSmPMVmSsdCjqg+GprVZmrj4OxuO0MW98V6plnTukmFDenq2eGj1FIWjjZ6UH7H2i9ZzHTVWCCBEQaC7RZh55ocFSB8XzqAzoNaUwOtpGJ3Usj6Fut8AZvfV9m0IF6KwtUyBu/vobSLU3fLr9vmJTZzniXaGja6T6+PdHgnfWnULH3hhlE4hQTmPUN2Vq1cN495MKbPKi/EUfkQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jwt-secret

