apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmeit-se
spec:
  secretName: tmeit-se-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - tmeit.se
  - www.tmeit.se
