apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- issuers.yaml
- certificate.yaml

# Inject cloudflare-api-token into a Kubernetes secret
secretGenerator:
- name: cloudflare-api-token-secret
  files:
    - cloudflare-api-token

generatorOptions:
  disableNameSuffixHash: true
