apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

replicas:
- name: tmeit-app
  count: 3

resources:
- tmeit-app/service.yaml
- tmeit-app/sealedsecret.yaml
- postgres/sealedsecret.yaml
- run-migrations/job.yaml
- operators
- certificate

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tmeit-app
    path: tmeit-app/init_container_patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tmeit-app
    path: tmeit-app/set_image_tag.json
  - target:
      group: batch
      version: v1
      kind: Job
      name: run-migrations
    path: run-migrations/set_image_tag.json
