from .send_test_email_to_member import send_test_email_to_member
from .send_test_email_to_dkimvalidator import send_test_email_to_dkimvalidator

functions = [send_test_email_to_member, send_test_email_to_dkimvalidator]
