- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "50m"
      memory: "80Mi"
      ephemeral-storage: 50Mi
    limits:
      cpu: "500m"
      memory: "160Mi"
      ephemeral-storage: 500Mi