# Job that runs all migrations for the production cluster

apiVersion: batch/v1
kind: Job
metadata:
  name: run-migrations
  labels:
    job: tmeit-db
spec:
  template:
    metadata:
      labels:
        job: tmeit-db
    spec:
      dnsConfig: # Fix DNS resolution in Alpine 3.11 https://github.com/kubernetes/kubernetes/issues/64924 https://github.com/gliderlabs/docker-alpine/issues/539
        options:
          - name: ndots
            value: "1"
      containers:
      - name: script
        image: tmeit-run-migrations:0.4.0
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kubegres-passwords
                key: tmeitBackendUserPassword
        resources:
          requests:
            cpu: "100m"
            memory: "40Mi"
            ephemeral-storage: 200Mi
          limits:
            cpu: "1"
            memory: "200Mi"
            ephemeral-storage: 500Mi
        securityContext:
          readOnlyRootFilesystem: true
      securityContext:
        runAsUser: 20001
        runAsGroup: 20001
      restartPolicy: Never
  backoffLimit: 10
