apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 20m
        memory: 40Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 100m
        memory: 80Mi
        ephemeral-storage: 500Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 40m
        memory: 50Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 200m
        memory: 100Mi
        ephemeral-storage: 500Mi
