apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 50m
      limits:
        cpu: 100m
        memory: 50Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 100Mi