apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 8m
        memory: 20Mi
      limits:
        cpu: 80m
        memory: 40Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 10m
        memory: 25Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
        ephemeral-storage: 500Mi
