name: Push and publish app

on:
  push:
    branches:
      - master

env:
  TMEIT_JLH_NAME_CA_BASE64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTXpneU1UUTNNakV3SGhjTk1qRXhNVEk1TVRrek9EUXhXaGNOTXpFeE1USTNNVGt6T0RReApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTXpneU1UUTNNakV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUMVBkZGhUUHZSSVdTWWw1T2tDZEpESThDMWlzc3VmT1BYZCtCWFgwNTMKU1VzWCtRVjc3eEZDbjFwdUpSK0k3NmpYcWpyaGd3b044T2g0dVFiTkNtcUdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVBQbUZkUU5paHZiUWZuVUJVRDJWCm9PN1BsbUl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnU1JDd2dQdmRpQ2k4MjNPV2dIdTQ1cVdMUlFhR2prY2sKT21WWjlHU0IzbzBDSVFEMVRaTVRvakJJRGxicm01QmxSbDR0Z2tCM3lsNVQweWRQM01aYUtqQ0xCZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

jobs:
  build-push:
    name: Build and push app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Get release version
        run: python release_utils/get_version.py gh-actions
        shell: sh
        id: release_version

      - name: Build OCI image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/tmeit/tmeit-app
          tags: "${{ steps.release_version.outputs.version }}"
          containerfiles: |-
            Containerfile

      - name: Export OCI image
        run: "podman save  --format docker-archive -o docker-container.tar ghcr.io/tmeit/tmeit-app:${{ steps.release_version.outputs.version }}"
      - name: Send image to publish-tag job # https://stackoverflow.com/a/57877438
        uses: actions/upload-artifact@v3
        with:
          name: "tmeit-app-image"
          path: "docker-container.tar"

      - name: Log in to gh registry
        uses: redhat-actions/podman-login@v1
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: "ghcr.io/tmeit"
      - name: Publish tmeit-app OCI image
        run: "podman push ghcr.io/tmeit/tmeit-app:${{ steps.release_version.outputs.version }}"
      - name: Setup KUBECONFIG
        uses: vbem/kubeconfig4sa@v1
        with: # Super useful action with good docs on k8s SAs https://github.com/vbem/kubeconfig4sa
          server: ${{ secrets.JLH_CLUSTER_URL}}
          ca-base64: ${{ env.TMEIT_JLH_NAME_CA_BASE64 }}
          token: ${{ secrets.TMEIT_JLH_NAME_SA_TOKEN}}
          namespace: tmeit
          # Note: this account on the JLH cluster has limited permissions. See the RBAC configuration in the jlh-h5b repo.
          # https://github.com/JustinLex/jlh-h5b/blob/main/applications/tmeit/rbac.yaml

      - name: 'Push manifests to prod'
        run: |
          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/v1.24.0/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          chmod +x kubectl
          kubectl apply -k deploy/tmeit-jlh-name/
# kubectl 1.24.0 has kustomize 4.5.4 built in

  publish-tag:
    name: Publish GH release
    runs-on: ubuntu-latest
    needs: build-push # Run after push so that we can get the docker image for publishing
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Get release version
        run: python release_utils/get_version.py gh-actions
        shell: sh
        id: release_version
      - name: Build k8s manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: '4.5.4'
          command: |-
            kustomize build deploy/tmeit-jlh-name -o k8s-manifests.yaml
      - name: Receive image from build-push job # https://stackoverflow:com/a/57877438
        uses: actions/download-artifact@v3
        with:
          name: "tmeit-app-image"
      - name: Create git tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CUSTOM_TAG: "${{ steps.release_version.outputs.version }}"
      - name: Generate changelog
        uses: loopwerk/tag-changelog@v1
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GH release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.release_version.outputs.version }}"
          body: "${{ steps.changelog.outputs.changelog }}"
          files: |
            docker-container.tar
            k8s-manifests.yaml
