name: Run tests
on:
  pull_request:
    branches:
      - master
jobs:
  version-incremented: # checks that version has been incremented in node, python, and deployment. And that they match.
    name: Are version numbers incremented
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to get git tag list due to the way Git works
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Check versions
        run: python release_utils/check-tag-incremented.py
        shell: sh
  lint-kustomization:
    name: Lint Kustomize/Kubernetes
    runs-on: ubuntu-22.04
    steps:
      - name: 'Build dev manifests'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: '4.5.4'
          command: |-
            kustomize build deploy/dev -o dev-rendered.yaml
      - name: 'Build tmeit.jlh.name manifests'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: '4.5.4'
          command: |-
            kustomize build deploy/tmeit-jlh-name -o jlh-rendered.yaml
#      - name: 'Build tmeit.se manifests'
#        uses: stefanprodan/kube-tools@v1
#        with:
#          kustomize: '4.5.4'
#          command: |
#            kustomize build deploy/tmeit-se -o tmeit-se-rendered.yaml
      - uses: azure/setup-kubectl@v2.0
      - name: 'Validate kubernetes manifests'
        uses: azure/k8s-lint@v1
        with:
          lintType: dryrun
          manifests: |
            dev-rendered.yaml
            deploy/tmeit-jlh-name
  lint-gh-actions:
    name: Lint GH Actions workflows
    runs-on: ubuntu-22.04
    steps:
      - uses: reviewdog/action-actionlint@v1
  test-app: # do a build (which lints and runs tests)
    name: Build and test app
    runs-on: ubuntu-22.04
    steps:
      - name: Build containers
        uses: redhat-actions/buildah-build@v2
        with:
          image: tmeit-app
          containerfiles: |-
            Containerfile-skip-tests
            Containerfile
