name: Run pr tests
on:
  pull_request:
    branches:
      - master
jobs:
  version-incremented: # checks that version has been incremented in node, python, and deployment. And that they match.
    name: Are version numbers incremented
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to get git tag list due to the way Git works
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Check versions
        run: python release_utils/check-tag-incremented.py
        shell: sh
  lint-kustomization:
    name: Lint Kustomize/Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Setup KUBECONFIG
        uses: vbem/kubeconfig4sa@v1
        with:
          server: ${{ secrets.JLH_CLUSTER_URL}}
          ca-base64: ${{ env.TMEIT_JLH_NAME_CA_BASE64 }}
          token: ${{ secrets.TMEIT_JLH_NAME_SA_TOKEN}}
          namespace: tmeit
      - name: 'Dry-run apply all environments'
        run: |
          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/v1.24.0/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          chmod +x kubectl
          kubectl apply --dry-run=client -o yaml -k deploy/dev/
          kubectl apply --dry-run=client -o yaml -k deploy/tmeit-jlh-name/
  lint-gh-actions:
    name: Lint GH Actions workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - uses: reviewdog/action-actionlint@v1
  test-app: # do a build (which lints and runs tests)
    name: Build and test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Build containers
        uses: redhat-actions/buildah-build@v2
        with:
          image: tmeit-app
          containerfiles: |-
            Containerfile-skip-tests
            Containerfile
