name: Lint and test code before it is pulled into master
on:
  pull_request:
    branches:
      - master
jobs:
  version-incremented: # checks that version has been incremented in node, python, and deployment. And that they match.
    name: Is version incremented
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to get git tag list due to the way Git works
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Check versions
        run: python release_utils/check-tag-incremented.py
        shell: sh
  lint-kustomization:
    name: Lint and Test Kustomize/Kubernetes
    runs-on: ubuntu-22.04
    steps:
      - name: 'Build dev manifests'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '4.5.4'
          kustomize_build_dir: 'deploy/dev'
          kustomize_output_file: "dev-rendered.yaml"
      - name: 'Build tmeit.jlh.name manifests'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '4.5.4'
          kustomize_build_dir: 'deploy/tmeit-jlh-name'
          kustomize_output_file: "jlh-rendered.yaml"
#      - name: 'Build tmeit.se manifests'
#        uses: karancode/kustomize-github-action@master
#        with:
#          kustomize_version: '4.5.4'
#          kustomize_build_dir: 'deploy/tmeit-se'
#          kustomize_output_file: "tmeit-se-rendered.yaml"
      - uses: azure/setup-kubectl@v2.0
      - name: 'Validate kubernetes manifests'
        uses: azure/k8s-lint@v1
        with:
          lintType: dryrun
          manifests: |
            dev-rendered.yaml
            deploy/tmeit-jlh-name
  lint-gh-actions:
    name: Lint Github Actions workflows
    runs-on: ubuntu-22.04
    steps:
      - uses: reviewdog/action-actionlint@v1
  test-app: # do a build (which lints and runs tests)
    name: Test app
    runs-on: ubuntu-22.04
    steps:
      - name: Build containers
        uses: redhat-actions/buildah-build@v2
        with:
          image: tmeit-app
          containerfiles: |-
            Containerfile-skip-tests
            Containerfile
