apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

replicas:
- name: tmeit-app
  count: 3

resources:
- tmeit-app/service.yaml
- postgres/sealedsecret.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tmeit-app
    path: tmeit-app/set_image_tag.json
