apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
- service.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tmeit-app
    path: set_image_tag.json
